//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamAssessmentWebAPI.ExamWCF {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SubTopic", Namespace="http://schemas.datacontract.org/2004/07/LMS1701.EA.SOAPAPI")]
    [System.SerializableAttribute()]
    public partial class SubTopic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Subtopic_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subtopic_NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Subtopic_ID {
            get {
                return this.Subtopic_IDField;
            }
            set {
                if ((this.Subtopic_IDField.Equals(value) != true)) {
                    this.Subtopic_IDField = value;
                    this.RaisePropertyChanged("Subtopic_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subtopic_Name {
            get {
                return this.Subtopic_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Subtopic_NameField, value) != true)) {
                    this.Subtopic_NameField = value;
                    this.RaisePropertyChanged("Subtopic_Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Answers", Namespace="http://schemas.datacontract.org/2004/07/LMS1701.EA.SOAPAPI")]
    [System.SerializableAttribute()]
    public partial class Answers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Answer1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PKIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamAssessmentWebAPI.ExamWCF.Correct correctField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Answer1 {
            get {
                return this.Answer1Field;
            }
            set {
                if ((object.ReferenceEquals(this.Answer1Field, value) != true)) {
                    this.Answer1Field = value;
                    this.RaisePropertyChanged("Answer1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PKID {
            get {
                return this.PKIDField;
            }
            set {
                if ((this.PKIDField.Equals(value) != true)) {
                    this.PKIDField = value;
                    this.RaisePropertyChanged("PKID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamAssessmentWebAPI.ExamWCF.Correct correct {
            get {
                return this.correctField;
            }
            set {
                if ((object.ReferenceEquals(this.correctField, value) != true)) {
                    this.correctField = value;
                    this.RaisePropertyChanged("correct");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Correct", Namespace="http://schemas.datacontract.org/2004/07/LMS1701.EA.SOAPAPI")]
    [System.SerializableAttribute()]
    public partial class Correct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isCorrectField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isCorrect {
            get {
                return this.isCorrectField;
            }
            set {
                if ((this.isCorrectField.Equals(value) != true)) {
                    this.isCorrectField = value;
                    this.RaisePropertyChanged("isCorrect");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://schemas.datacontract.org/2004/07/LMS1701.EA.SOAPAPI")]
    [System.SerializableAttribute()]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Subject_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Subject_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamAssessmentWebAPI.ExamWCF.Category[] listCatField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Subject_ID {
            get {
                return this.Subject_IDField;
            }
            set {
                if ((this.Subject_IDField.Equals(value) != true)) {
                    this.Subject_IDField = value;
                    this.RaisePropertyChanged("Subject_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Subject_Name {
            get {
                return this.Subject_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Subject_NameField, value) != true)) {
                    this.Subject_NameField = value;
                    this.RaisePropertyChanged("Subject_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamAssessmentWebAPI.ExamWCF.Category[] listCat {
            get {
                return this.listCatField;
            }
            set {
                if ((object.ReferenceEquals(this.listCatField, value) != true)) {
                    this.listCatField = value;
                    this.RaisePropertyChanged("listCat");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://schemas.datacontract.org/2004/07/LMS1701.EA.SOAPAPI")]
    [System.SerializableAttribute()]
    public partial class Category : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Categories_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Categories_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamAssessmentWebAPI.ExamWCF.SubTopic[] subtopicsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Categories_ID {
            get {
                return this.Categories_IDField;
            }
            set {
                if ((this.Categories_IDField.Equals(value) != true)) {
                    this.Categories_IDField = value;
                    this.RaisePropertyChanged("Categories_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Categories_Name {
            get {
                return this.Categories_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Categories_NameField, value) != true)) {
                    this.Categories_NameField = value;
                    this.RaisePropertyChanged("Categories_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamAssessmentWebAPI.ExamWCF.SubTopic[] subtopics {
            get {
                return this.subtopicsField;
            }
            set {
                if ((object.ReferenceEquals(this.subtopicsField, value) != true)) {
                    this.subtopicsField = value;
                    this.RaisePropertyChanged("subtopics");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamTemplate", Namespace="http://schemas.datacontract.org/2004/07/LMS1701.EA.SOAPAPI")]
    [System.SerializableAttribute()]
    public partial class ExamTemplate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreatedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamAssessmentWebAPI.ExamWCF.ExamQuestion[] ExamQuestionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamTemplateIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamTemplateNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamAssessmentWebAPI.ExamWCF.Examtype ExamTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PKIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedDate {
            get {
                return this.CreatedDateField;
            }
            set {
                if ((this.CreatedDateField.Equals(value) != true)) {
                    this.CreatedDateField = value;
                    this.RaisePropertyChanged("CreatedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamAssessmentWebAPI.ExamWCF.ExamQuestion[] ExamQuestions {
            get {
                return this.ExamQuestionsField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamQuestionsField, value) != true)) {
                    this.ExamQuestionsField = value;
                    this.RaisePropertyChanged("ExamQuestions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExamTemplateID {
            get {
                return this.ExamTemplateIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamTemplateIDField, value) != true)) {
                    this.ExamTemplateIDField = value;
                    this.RaisePropertyChanged("ExamTemplateID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExamTemplateName {
            get {
                return this.ExamTemplateNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamTemplateNameField, value) != true)) {
                    this.ExamTemplateNameField = value;
                    this.RaisePropertyChanged("ExamTemplateName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamAssessmentWebAPI.ExamWCF.Examtype ExamType {
            get {
                return this.ExamTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamTypeField, value) != true)) {
                    this.ExamTypeField = value;
                    this.RaisePropertyChanged("ExamType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PKID {
            get {
                return this.PKIDField;
            }
            set {
                if ((this.PKIDField.Equals(value) != true)) {
                    this.PKIDField = value;
                    this.RaisePropertyChanged("PKID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Examtype", Namespace="http://schemas.datacontract.org/2004/07/LMS1701.EA.SOAPAPI")]
    [System.SerializableAttribute()]
    public partial class Examtype : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamAssessmentWebAPI.ExamWCF.ExamTemplate[] ExamTemplatesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamTypeNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PKIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamAssessmentWebAPI.ExamWCF.ExamTemplate[] ExamTemplates {
            get {
                return this.ExamTemplatesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamTemplatesField, value) != true)) {
                    this.ExamTemplatesField = value;
                    this.RaisePropertyChanged("ExamTemplates");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExamTypeName {
            get {
                return this.ExamTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamTypeNameField, value) != true)) {
                    this.ExamTypeNameField = value;
                    this.RaisePropertyChanged("ExamTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PKID {
            get {
                return this.PKIDField;
            }
            set {
                if ((this.PKIDField.Equals(value) != true)) {
                    this.PKIDField = value;
                    this.RaisePropertyChanged("PKID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExamQuestion", Namespace="http://schemas.datacontract.org/2004/07/LMS1701.EA.SOAPAPI")]
    [System.SerializableAttribute()]
    public partial class ExamQuestion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamQuestionIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExamQuestionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamAssessmentWebAPI.ExamWCF.Category[] ExamQuestion_CategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PKIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamAssessmentWebAPI.ExamWCF.QuestionType QuestionTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamAssessmentWebAPI.ExamWCF.Question[] questField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExamQuestionID {
            get {
                return this.ExamQuestionIDField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamQuestionIDField, value) != true)) {
                    this.ExamQuestionIDField = value;
                    this.RaisePropertyChanged("ExamQuestionID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExamQuestionName {
            get {
                return this.ExamQuestionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamQuestionNameField, value) != true)) {
                    this.ExamQuestionNameField = value;
                    this.RaisePropertyChanged("ExamQuestionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamAssessmentWebAPI.ExamWCF.Category[] ExamQuestion_Categories {
            get {
                return this.ExamQuestion_CategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.ExamQuestion_CategoriesField, value) != true)) {
                    this.ExamQuestion_CategoriesField = value;
                    this.RaisePropertyChanged("ExamQuestion_Categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PKID {
            get {
                return this.PKIDField;
            }
            set {
                if ((this.PKIDField.Equals(value) != true)) {
                    this.PKIDField = value;
                    this.RaisePropertyChanged("PKID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamAssessmentWebAPI.ExamWCF.QuestionType QuestionType {
            get {
                return this.QuestionTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTypeField, value) != true)) {
                    this.QuestionTypeField = value;
                    this.RaisePropertyChanged("QuestionType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamAssessmentWebAPI.ExamWCF.Question[] quest {
            get {
                return this.questField;
            }
            set {
                if ((object.ReferenceEquals(this.questField, value) != true)) {
                    this.questField = value;
                    this.RaisePropertyChanged("quest");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="QuestionType", Namespace="http://schemas.datacontract.org/2004/07/LMS1701.EA.SOAPAPI")]
    [System.SerializableAttribute()]
    public partial class QuestionType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PKIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QuestionTypeNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PKID {
            get {
                return this.PKIDField;
            }
            set {
                if ((this.PKIDField.Equals(value) != true)) {
                    this.PKIDField = value;
                    this.RaisePropertyChanged("PKID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QuestionTypeName {
            get {
                return this.QuestionTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.QuestionTypeNameField, value) != true)) {
                    this.QuestionTypeNameField = value;
                    this.RaisePropertyChanged("QuestionTypeName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Question", Namespace="http://schemas.datacontract.org/2004/07/LMS1701.EA.SOAPAPI")]
    [System.SerializableAttribute()]
    public partial class Question : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ExamAssessmentWebAPI.ExamWCF.Answers[] AnswersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PKIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExamAssessmentWebAPI.ExamWCF.Answers[] Answers {
            get {
                return this.AnswersField;
            }
            set {
                if ((object.ReferenceEquals(this.AnswersField, value) != true)) {
                    this.AnswersField = value;
                    this.RaisePropertyChanged("Answers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PKID {
            get {
                return this.PKIDField;
            }
            set {
                if ((this.PKIDField.Equals(value) != true)) {
                    this.PKIDField = value;
                    this.RaisePropertyChanged("PKID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ExamWCF.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubtopicList", ReplyAction="http://tempuri.org/IService1/GetSubtopicListResponse")]
        ExamAssessmentWebAPI.ExamWCF.SubTopic[] GetSubtopicList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSubtopicList", ReplyAction="http://tempuri.org/IService1/GetSubtopicListResponse")]
        System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.SubTopic[]> GetSubtopicListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAnswersQuestion", ReplyAction="http://tempuri.org/IService1/GetAnswersQuestionResponse")]
        ExamAssessmentWebAPI.ExamWCF.Answers[] GetAnswersQuestion(int Questid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAnswersQuestion", ReplyAction="http://tempuri.org/IService1/GetAnswersQuestionResponse")]
        System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.Answers[]> GetAnswersQuestionAsync(int Questid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllSubject", ReplyAction="http://tempuri.org/IService1/GetAllSubjectResponse")]
        ExamAssessmentWebAPI.ExamWCF.Subject[] GetAllSubject();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllSubject", ReplyAction="http://tempuri.org/IService1/GetAllSubjectResponse")]
        System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.Subject[]> GetAllSubjectAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getExamTemplate", ReplyAction="http://tempuri.org/IService1/getExamTemplateResponse")]
        ExamAssessmentWebAPI.ExamWCF.ExamTemplate getExamTemplate(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/getExamTemplate", ReplyAction="http://tempuri.org/IService1/getExamTemplateResponse")]
        System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.ExamTemplate> getExamTemplateAsync(string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllQuestions", ReplyAction="http://tempuri.org/IService1/GetAllQuestionsResponse")]
        ExamAssessmentWebAPI.ExamWCF.Question[] GetAllQuestions();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllQuestions", ReplyAction="http://tempuri.org/IService1/GetAllQuestionsResponse")]
        System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.Question[]> GetAllQuestionsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllExamQuestion", ReplyAction="http://tempuri.org/IService1/GetAllExamQuestionResponse")]
        ExamAssessmentWebAPI.ExamWCF.ExamQuestion[] GetAllExamQuestion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllExamQuestion", ReplyAction="http://tempuri.org/IService1/GetAllExamQuestionResponse")]
        System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.ExamQuestion[]> GetAllExamQuestionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddExistingCategory", ReplyAction="http://tempuri.org/IService1/spAddExistingCategoryResponse")]
        void spAddExistingCategory(string subject, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddExistingCategory", ReplyAction="http://tempuri.org/IService1/spAddExistingCategoryResponse")]
        System.Threading.Tasks.Task spAddExistingCategoryAsync(string subject, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddExistingSubtopicToCategory", ReplyAction="http://tempuri.org/IService1/spAddExistingSubtopicToCategoryResponse")]
        void spAddExistingSubtopicToCategory(string subtopic, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddExistingSubtopicToCategory", ReplyAction="http://tempuri.org/IService1/spAddExistingSubtopicToCategoryResponse")]
        System.Threading.Tasks.Task spAddExistingSubtopicToCategoryAsync(string subtopic, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddNewCategoryType", ReplyAction="http://tempuri.org/IService1/spAddNewCategoryTypeResponse")]
        void spAddNewCategoryType(string subject, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddNewCategoryType", ReplyAction="http://tempuri.org/IService1/spAddNewCategoryTypeResponse")]
        System.Threading.Tasks.Task spAddNewCategoryTypeAsync(string subject, string category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddQuestionAsExamQuestion", ReplyAction="http://tempuri.org/IService1/spAddQuestionAsExamQuestionResponse")]
        void spAddQuestionAsExamQuestion(string ExamQuestionID, int QuestionID, string name, int QuestionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddQuestionAsExamQuestion", ReplyAction="http://tempuri.org/IService1/spAddQuestionAsExamQuestionResponse")]
        System.Threading.Tasks.Task spAddQuestionAsExamQuestionAsync(string ExamQuestionID, int QuestionID, string name, int QuestionType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddQuestionCategories", ReplyAction="http://tempuri.org/IService1/AddQuestionCategoriesResponse")]
        void AddQuestionCategories(string Categories, string ExamQuestionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddQuestionCategories", ReplyAction="http://tempuri.org/IService1/AddQuestionCategoriesResponse")]
        System.Threading.Tasks.Task AddQuestionCategoriesAsync(string Categories, string ExamQuestionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddQuestionToAnswer", ReplyAction="http://tempuri.org/IService1/spAddQuestionToAnswerResponse")]
        void spAddQuestionToAnswer(int QuestionID, int AnswerID, bool isCorrect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddQuestionToAnswer", ReplyAction="http://tempuri.org/IService1/spAddQuestionToAnswerResponse")]
        System.Threading.Tasks.Task spAddQuestionToAnswerAsync(int QuestionID, int AnswerID, bool isCorrect);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddQuestionToExam", ReplyAction="http://tempuri.org/IService1/spAddQuestionToExamResponse")]
        void spAddQuestionToExam(string ExamID, string ExamQuestionID, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddQuestionToExam", ReplyAction="http://tempuri.org/IService1/spAddQuestionToExamResponse")]
        System.Threading.Tasks.Task spAddQuestionToExamAsync(string ExamID, string ExamQuestionID, int weight);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddSubtopicType", ReplyAction="http://tempuri.org/IService1/spAddSubtopicTypeResponse")]
        void spAddSubtopicType(string Subtopics, string Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spAddSubtopicType", ReplyAction="http://tempuri.org/IService1/spAddSubtopicTypeResponse")]
        System.Threading.Tasks.Task spAddSubtopicTypeAsync(string Subtopics, string Category);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spDeleteQuestionCategory", ReplyAction="http://tempuri.org/IService1/spDeleteQuestionCategoryResponse")]
        void spDeleteQuestionCategory(string Categories, string ExamID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spDeleteQuestionCategory", ReplyAction="http://tempuri.org/IService1/spDeleteQuestionCategoryResponse")]
        System.Threading.Tasks.Task spDeleteQuestionCategoryAsync(string Categories, string ExamID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteQuestionCategory", ReplyAction="http://tempuri.org/IService1/DeleteQuestionCategoryResponse")]
        void DeleteQuestionCategory(string Category, string ExamQID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteQuestionCategory", ReplyAction="http://tempuri.org/IService1/DeleteQuestionCategoryResponse")]
        System.Threading.Tasks.Task DeleteQuestionCategoryAsync(string Category, string ExamQID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spRemoveAnswerFromQuestion", ReplyAction="http://tempuri.org/IService1/spRemoveAnswerFromQuestionResponse")]
        void spRemoveAnswerFromQuestion(int QuestionID, int AnswerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spRemoveAnswerFromQuestion", ReplyAction="http://tempuri.org/IService1/spRemoveAnswerFromQuestionResponse")]
        System.Threading.Tasks.Task spRemoveAnswerFromQuestionAsync(int QuestionID, int AnswerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spRemoveQuestionAsExamQuestion", ReplyAction="http://tempuri.org/IService1/spRemoveQuestionAsExamQuestionResponse")]
        void spRemoveQuestionAsExamQuestion(string ExamQuestionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spRemoveQuestionAsExamQuestion", ReplyAction="http://tempuri.org/IService1/spRemoveQuestionAsExamQuestionResponse")]
        System.Threading.Tasks.Task spRemoveQuestionAsExamQuestionAsync(string ExamQuestionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spRemoveQuestionFromExam", ReplyAction="http://tempuri.org/IService1/spRemoveQuestionFromExamResponse")]
        void spRemoveQuestionFromExam(string ExamQuestionID, string QuestionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/spRemoveQuestionFromExam", ReplyAction="http://tempuri.org/IService1/spRemoveQuestionFromExamResponse")]
        System.Threading.Tasks.Task spRemoveQuestionFromExamAsync(string ExamQuestionID, string QuestionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSubject", ReplyAction="http://tempuri.org/IService1/AddSubjectResponse")]
        void AddSubject(string SubjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSubject", ReplyAction="http://tempuri.org/IService1/AddSubjectResponse")]
        System.Threading.Tasks.Task AddSubjectAsync(string SubjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSubtopic", ReplyAction="http://tempuri.org/IService1/DeleteSubtopicResponse")]
        void DeleteSubtopic(string SubtopicName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSubtopic", ReplyAction="http://tempuri.org/IService1/DeleteSubtopicResponse")]
        System.Threading.Tasks.Task DeleteSubtopicAsync(string SubtopicName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveSubtopicFromCategory", ReplyAction="http://tempuri.org/IService1/RemoveSubtopicFromCategoryResponse")]
        void RemoveSubtopicFromCategory(string SubtopicName, string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveSubtopicFromCategory", ReplyAction="http://tempuri.org/IService1/RemoveSubtopicFromCategoryResponse")]
        System.Threading.Tasks.Task RemoveSubtopicFromCategoryAsync(string SubtopicName, string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddExamQuestion", ReplyAction="http://tempuri.org/IService1/AddExamQuestionResponse")]
        void AddExamQuestion(ExamAssessmentWebAPI.ExamWCF.ExamQuestion examQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddExamQuestion", ReplyAction="http://tempuri.org/IService1/AddExamQuestionResponse")]
        System.Threading.Tasks.Task AddExamQuestionAsync(ExamAssessmentWebAPI.ExamWCF.ExamQuestion examQuestion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategory", ReplyAction="http://tempuri.org/IService1/DeleteCategoryResponse")]
        void DeleteCategory(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteCategory", ReplyAction="http://tempuri.org/IService1/DeleteCategoryResponse")]
        System.Threading.Tasks.Task DeleteCategoryAsync(string CategoryName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAnswer", ReplyAction="http://tempuri.org/IService1/AddAnswerResponse")]
        void AddAnswer(int QuestionID, string Answer, bool IC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddAnswer", ReplyAction="http://tempuri.org/IService1/AddAnswerResponse")]
        System.Threading.Tasks.Task AddAnswerAsync(int QuestionID, string Answer, bool IC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAnswer", ReplyAction="http://tempuri.org/IService1/DeleteAnswerResponse")]
        void DeleteAnswer(string Answerdesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteAnswer", ReplyAction="http://tempuri.org/IService1/DeleteAnswerResponse")]
        System.Threading.Tasks.Task DeleteAnswerAsync(string Answerdesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveCategoryFromSubject", ReplyAction="http://tempuri.org/IService1/RemoveCategoryFromSubjectResponse")]
        void RemoveCategoryFromSubject(string CategoryName, string SubjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveCategoryFromSubject", ReplyAction="http://tempuri.org/IService1/RemoveCategoryFromSubjectResponse")]
        System.Threading.Tasks.Task RemoveCategoryFromSubjectAsync(string CategoryName, string SubjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSubject", ReplyAction="http://tempuri.org/IService1/DeleteSubjectResponse")]
        void DeleteSubject(string SubjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSubject", ReplyAction="http://tempuri.org/IService1/DeleteSubjectResponse")]
        System.Threading.Tasks.Task DeleteSubjectAsync(string SubjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAnswer", ReplyAction="http://tempuri.org/IService1/UpdateAnswerResponse")]
        void UpdateAnswer(int answerid, string newdesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateAnswer", ReplyAction="http://tempuri.org/IService1/UpdateAnswerResponse")]
        System.Threading.Tasks.Task UpdateAnswerAsync(int answerid, string newdesc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteExam", ReplyAction="http://tempuri.org/IService1/DeleteExamResponse")]
        void DeleteExam(string SubjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteExam", ReplyAction="http://tempuri.org/IService1/DeleteExamResponse")]
        System.Threading.Tasks.Task DeleteExamAsync(string SubjectName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewExam", ReplyAction="http://tempuri.org/IService1/AddNewExamResponse")]
        void AddNewExam(string ExamTemplateName, string ExamTemplateID, string ExamTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddNewExam", ReplyAction="http://tempuri.org/IService1/AddNewExamResponse")]
        System.Threading.Tasks.Task AddNewExamAsync(string ExamTemplateName, string ExamTemplateID, string ExamTypeName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExamIDList", ReplyAction="http://tempuri.org/IService1/GetExamIDListResponse")]
        string[] GetExamIDList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetExamIDList", ReplyAction="http://tempuri.org/IService1/GetExamIDListResponse")]
        System.Threading.Tasks.Task<string[]> GetExamIDListAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ExamAssessmentWebAPI.ExamWCF.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ExamAssessmentWebAPI.ExamWCF.IService1>, ExamAssessmentWebAPI.ExamWCF.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ExamAssessmentWebAPI.ExamWCF.SubTopic[] GetSubtopicList() {
            return base.Channel.GetSubtopicList();
        }
        
        public System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.SubTopic[]> GetSubtopicListAsync() {
            return base.Channel.GetSubtopicListAsync();
        }
        
        public ExamAssessmentWebAPI.ExamWCF.Answers[] GetAnswersQuestion(int Questid) {
            return base.Channel.GetAnswersQuestion(Questid);
        }
        
        public System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.Answers[]> GetAnswersQuestionAsync(int Questid) {
            return base.Channel.GetAnswersQuestionAsync(Questid);
        }
        
        public ExamAssessmentWebAPI.ExamWCF.Subject[] GetAllSubject() {
            return base.Channel.GetAllSubject();
        }
        
        public System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.Subject[]> GetAllSubjectAsync() {
            return base.Channel.GetAllSubjectAsync();
        }
        
        public ExamAssessmentWebAPI.ExamWCF.ExamTemplate getExamTemplate(string id) {
            return base.Channel.getExamTemplate(id);
        }
        
        public System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.ExamTemplate> getExamTemplateAsync(string id) {
            return base.Channel.getExamTemplateAsync(id);
        }
        
        public ExamAssessmentWebAPI.ExamWCF.Question[] GetAllQuestions() {
            return base.Channel.GetAllQuestions();
        }
        
        public System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.Question[]> GetAllQuestionsAsync() {
            return base.Channel.GetAllQuestionsAsync();
        }
        
        public ExamAssessmentWebAPI.ExamWCF.ExamQuestion[] GetAllExamQuestion() {
            return base.Channel.GetAllExamQuestion();
        }
        
        public System.Threading.Tasks.Task<ExamAssessmentWebAPI.ExamWCF.ExamQuestion[]> GetAllExamQuestionAsync() {
            return base.Channel.GetAllExamQuestionAsync();
        }
        
        public void spAddExistingCategory(string subject, string category) {
            base.Channel.spAddExistingCategory(subject, category);
        }
        
        public System.Threading.Tasks.Task spAddExistingCategoryAsync(string subject, string category) {
            return base.Channel.spAddExistingCategoryAsync(subject, category);
        }
        
        public void spAddExistingSubtopicToCategory(string subtopic, string category) {
            base.Channel.spAddExistingSubtopicToCategory(subtopic, category);
        }
        
        public System.Threading.Tasks.Task spAddExistingSubtopicToCategoryAsync(string subtopic, string category) {
            return base.Channel.spAddExistingSubtopicToCategoryAsync(subtopic, category);
        }
        
        public void spAddNewCategoryType(string subject, string category) {
            base.Channel.spAddNewCategoryType(subject, category);
        }
        
        public System.Threading.Tasks.Task spAddNewCategoryTypeAsync(string subject, string category) {
            return base.Channel.spAddNewCategoryTypeAsync(subject, category);
        }
        
        public void spAddQuestionAsExamQuestion(string ExamQuestionID, int QuestionID, string name, int QuestionType) {
            base.Channel.spAddQuestionAsExamQuestion(ExamQuestionID, QuestionID, name, QuestionType);
        }
        
        public System.Threading.Tasks.Task spAddQuestionAsExamQuestionAsync(string ExamQuestionID, int QuestionID, string name, int QuestionType) {
            return base.Channel.spAddQuestionAsExamQuestionAsync(ExamQuestionID, QuestionID, name, QuestionType);
        }
        
        public void AddQuestionCategories(string Categories, string ExamQuestionID) {
            base.Channel.AddQuestionCategories(Categories, ExamQuestionID);
        }
        
        public System.Threading.Tasks.Task AddQuestionCategoriesAsync(string Categories, string ExamQuestionID) {
            return base.Channel.AddQuestionCategoriesAsync(Categories, ExamQuestionID);
        }
        
        public void spAddQuestionToAnswer(int QuestionID, int AnswerID, bool isCorrect) {
            base.Channel.spAddQuestionToAnswer(QuestionID, AnswerID, isCorrect);
        }
        
        public System.Threading.Tasks.Task spAddQuestionToAnswerAsync(int QuestionID, int AnswerID, bool isCorrect) {
            return base.Channel.spAddQuestionToAnswerAsync(QuestionID, AnswerID, isCorrect);
        }
        
        public void spAddQuestionToExam(string ExamID, string ExamQuestionID, int weight) {
            base.Channel.spAddQuestionToExam(ExamID, ExamQuestionID, weight);
        }
        
        public System.Threading.Tasks.Task spAddQuestionToExamAsync(string ExamID, string ExamQuestionID, int weight) {
            return base.Channel.spAddQuestionToExamAsync(ExamID, ExamQuestionID, weight);
        }
        
        public void spAddSubtopicType(string Subtopics, string Category) {
            base.Channel.spAddSubtopicType(Subtopics, Category);
        }
        
        public System.Threading.Tasks.Task spAddSubtopicTypeAsync(string Subtopics, string Category) {
            return base.Channel.spAddSubtopicTypeAsync(Subtopics, Category);
        }
        
        public void spDeleteQuestionCategory(string Categories, string ExamID) {
            base.Channel.spDeleteQuestionCategory(Categories, ExamID);
        }
        
        public System.Threading.Tasks.Task spDeleteQuestionCategoryAsync(string Categories, string ExamID) {
            return base.Channel.spDeleteQuestionCategoryAsync(Categories, ExamID);
        }
        
        public void DeleteQuestionCategory(string Category, string ExamQID) {
            base.Channel.DeleteQuestionCategory(Category, ExamQID);
        }
        
        public System.Threading.Tasks.Task DeleteQuestionCategoryAsync(string Category, string ExamQID) {
            return base.Channel.DeleteQuestionCategoryAsync(Category, ExamQID);
        }
        
        public void spRemoveAnswerFromQuestion(int QuestionID, int AnswerID) {
            base.Channel.spRemoveAnswerFromQuestion(QuestionID, AnswerID);
        }
        
        public System.Threading.Tasks.Task spRemoveAnswerFromQuestionAsync(int QuestionID, int AnswerID) {
            return base.Channel.spRemoveAnswerFromQuestionAsync(QuestionID, AnswerID);
        }
        
        public void spRemoveQuestionAsExamQuestion(string ExamQuestionID) {
            base.Channel.spRemoveQuestionAsExamQuestion(ExamQuestionID);
        }
        
        public System.Threading.Tasks.Task spRemoveQuestionAsExamQuestionAsync(string ExamQuestionID) {
            return base.Channel.spRemoveQuestionAsExamQuestionAsync(ExamQuestionID);
        }
        
        public void spRemoveQuestionFromExam(string ExamQuestionID, string QuestionID) {
            base.Channel.spRemoveQuestionFromExam(ExamQuestionID, QuestionID);
        }
        
        public System.Threading.Tasks.Task spRemoveQuestionFromExamAsync(string ExamQuestionID, string QuestionID) {
            return base.Channel.spRemoveQuestionFromExamAsync(ExamQuestionID, QuestionID);
        }
        
        public void AddSubject(string SubjectName) {
            base.Channel.AddSubject(SubjectName);
        }
        
        public System.Threading.Tasks.Task AddSubjectAsync(string SubjectName) {
            return base.Channel.AddSubjectAsync(SubjectName);
        }
        
        public void DeleteSubtopic(string SubtopicName) {
            base.Channel.DeleteSubtopic(SubtopicName);
        }
        
        public System.Threading.Tasks.Task DeleteSubtopicAsync(string SubtopicName) {
            return base.Channel.DeleteSubtopicAsync(SubtopicName);
        }
        
        public void RemoveSubtopicFromCategory(string SubtopicName, string CategoryName) {
            base.Channel.RemoveSubtopicFromCategory(SubtopicName, CategoryName);
        }
        
        public System.Threading.Tasks.Task RemoveSubtopicFromCategoryAsync(string SubtopicName, string CategoryName) {
            return base.Channel.RemoveSubtopicFromCategoryAsync(SubtopicName, CategoryName);
        }
        
        public void AddExamQuestion(ExamAssessmentWebAPI.ExamWCF.ExamQuestion examQuestion) {
            base.Channel.AddExamQuestion(examQuestion);
        }
        
        public System.Threading.Tasks.Task AddExamQuestionAsync(ExamAssessmentWebAPI.ExamWCF.ExamQuestion examQuestion) {
            return base.Channel.AddExamQuestionAsync(examQuestion);
        }
        
        public void DeleteCategory(string CategoryName) {
            base.Channel.DeleteCategory(CategoryName);
        }
        
        public System.Threading.Tasks.Task DeleteCategoryAsync(string CategoryName) {
            return base.Channel.DeleteCategoryAsync(CategoryName);
        }
        
        public void AddAnswer(int QuestionID, string Answer, bool IC) {
            base.Channel.AddAnswer(QuestionID, Answer, IC);
        }
        
        public System.Threading.Tasks.Task AddAnswerAsync(int QuestionID, string Answer, bool IC) {
            return base.Channel.AddAnswerAsync(QuestionID, Answer, IC);
        }
        
        public void DeleteAnswer(string Answerdesc) {
            base.Channel.DeleteAnswer(Answerdesc);
        }
        
        public System.Threading.Tasks.Task DeleteAnswerAsync(string Answerdesc) {
            return base.Channel.DeleteAnswerAsync(Answerdesc);
        }
        
        public void RemoveCategoryFromSubject(string CategoryName, string SubjectName) {
            base.Channel.RemoveCategoryFromSubject(CategoryName, SubjectName);
        }
        
        public System.Threading.Tasks.Task RemoveCategoryFromSubjectAsync(string CategoryName, string SubjectName) {
            return base.Channel.RemoveCategoryFromSubjectAsync(CategoryName, SubjectName);
        }
        
        public void DeleteSubject(string SubjectName) {
            base.Channel.DeleteSubject(SubjectName);
        }
        
        public System.Threading.Tasks.Task DeleteSubjectAsync(string SubjectName) {
            return base.Channel.DeleteSubjectAsync(SubjectName);
        }
        
        public void UpdateAnswer(int answerid, string newdesc) {
            base.Channel.UpdateAnswer(answerid, newdesc);
        }
        
        public System.Threading.Tasks.Task UpdateAnswerAsync(int answerid, string newdesc) {
            return base.Channel.UpdateAnswerAsync(answerid, newdesc);
        }
        
        public void DeleteExam(string SubjectName) {
            base.Channel.DeleteExam(SubjectName);
        }
        
        public System.Threading.Tasks.Task DeleteExamAsync(string SubjectName) {
            return base.Channel.DeleteExamAsync(SubjectName);
        }
        
        public void AddNewExam(string ExamTemplateName, string ExamTemplateID, string ExamTypeName) {
            base.Channel.AddNewExam(ExamTemplateName, ExamTemplateID, ExamTypeName);
        }
        
        public System.Threading.Tasks.Task AddNewExamAsync(string ExamTemplateName, string ExamTemplateID, string ExamTypeName) {
            return base.Channel.AddNewExamAsync(ExamTemplateName, ExamTemplateID, ExamTypeName);
        }
        
        public string[] GetExamIDList() {
            return base.Channel.GetExamIDList();
        }
        
        public System.Threading.Tasks.Task<string[]> GetExamIDListAsync() {
            return base.Channel.GetExamIDListAsync();
        }
    }
}
